### ISSUE TITLE
All @ExtensiveSealed declaration combines state in all generated files resulting in compilation error when similar states are defined in different sealed Interfaces

### ISSUE THREAD

**Issue by chege4179** [skydoves/sealedx#4]
**Please complete the following information:**
- Library Version [e.g. v1.0.1]

**Describe the Bug:**
When 2 sealed interfaces are defined  with the @ExtensiveSealed with similar states the between both the sealed classes(The naming of the states are the same ) the processor generates files with duplicate states which results in a compilation error.In short it combines the states defined in all @ExtensiveSealed declarations into all generated states

**Expected Behavior:**
The processor should generate states for the models that are defined for a particular @ExtensiveSealed and not combine the states

**Comment by chege4179** [comment]
@skydoves

**Comment by skydoves** [comment]
Hey @chege4179, sorry for the late response. Could you give me some examples of this?

**Comment by chege4179** [comment]
I have tried to recreate the issue but it seems the issue was on my end. Sorry for the inconvenience. Feel free to close this issue 
And thank's for this amazing library
